### PR TITLE
chore: move posthog to peer dependency

### PR DESCRIPTION
**Pull request by pauldambra**
move posthog to being a peer dependency

### CODE REVIEW

**Comment by pauldambra** [comment]
@mariusandra do we have a way of releasing this to NPM yet?

**Review by mariusandra — APPROVED** [review]
There is a way. I'm now the maintainer! Tell me who to add, and you can push manually from `npm publish`

image


https://www.npmjs.com/package/next-use-posthog

**Comment by pauldambra** [comment]
add me 🥇 

npm username: pauldambra

**Comment by pauldambra** [comment]
Is this a breaking change? Bump major version?

**Review by benjackwhite — CHANGES_REQUESTED** [review]
I'm not sure how I feel about this tbh. If you have to install this npm package _as well as_ posthog-js to then get essentially 5 lines of code which are also somewhat buggy... Starts to undermine the worth of the repo 😅 

For now if we think it is the right call I'm happy to 👍  but then it definitely should be a major change as it is broken without dev engagement.

Major change makes me wish instead that we would consider implementing this as an optional import as part of `posthog-js` so that one could so something like

```tsx
import posthog from "posthog-js";
import { usePageviewTracker } from "posthog-js/nextjs";
import { useFeatureFlag } from "posthog-js/react";

posthog.init("key")

export const App = () => {
  usePageviewTracker();

  const myFlag = useFeatureFlag("test");
  return <div>{myFlag}</div>
}
```

**Comment by pauldambra** [comment]
> consider implementing this as an optional import as part of posthog-js

Yep, that's fair... this is a short-term fix the thing in front of us PR. That proposal is really nice though.

**Comment by NicolaGenesinJetty** [comment]
Sorry to chip in in this PR. Is this the package to use? It's not listed here https://posthog.com/docs/integrate/third-party/next-js

**Pull request merged**
